### ISSUE TITLE
Add flake8 to Github Actions

### ISSUE THREAD

**Issue by grenwi** [Leibniz-HBI/DBoeS-Automatization#20]
Fail if there are files with bad linter scores

**Comment by FlxVctr** [comment]
I've added a lint job here: https://github.com/Leibniz-HBI/DBoeS-Automatization/blob/master/.github/workflows/python-app.yml#L14

Based on https://github.com/marketplace/actions/lintly-flake8

Here's an example PR with intentional linter errors: #23 

Note that at the moment it's configured to raise new linter errors (i.e. made in the respective PR) only.

**Comment by FlxVctr** [comment]
set max line length to 127 (Github editor width)

**Comment by grenwi** [comment]
nice solution. let's see how much annoyed we will get by this ;)
