### ISSUE TITLE
Get twitter user handles for names

### ISSUE THREAD

**Issue by grenwi** [Leibniz-HBI/DBoeS-Automatization#30]
- search via API or scrape? (e.g. twint or twarc)
- search for full name + abbrev MdL | MdA | MdB | ...
- get n most probable user handles as ordered list

**Comment by FlxVctr** [comment]
I'd start working on this, using twint for simplicity's sake. (Otherwise we have to deal with OAuth etc.)

**Comment by FlxVctr** [comment]
Actually, have to take this back. Twint does not allow searching for users.

**Comment by FlxVctr** [comment]
Also could not find a possibility in twarc to search users. Instead of starting a PR to add the feature, I've used tweepy.

All changes here: https://github.com/Leibniz-HBI/DBoeS-Automatization/compare/30_get_twitter_user_handles

When starting all unit-tests or main.py a browser will open to authenticate a user (after having added app credentials to credentials.py) if there are no tokens for an authenticating Twitter account. For Github actions I have encrypted my credentials and changed the workflows accordingly.

So far there's now a function that returns the top results from Twitter for a real name [here](https://github.com/Leibniz-HBI/DBoeS-Automatization/compare/30_get_twitter_user_handles#diff-623fe638cc78bf475dc23ca644095d78a83616b0b9ace4c1abda469317618d3aR2)

The test [here](https://github.com/Leibniz-HBI/DBoeS-Automatization/compare/30_get_twitter_user_handles#diff-0994f7d80bd16f1a810ac5ee71bcfb28381c7baef4623b9d82fc1f0294de81feR25) should clarify the function.

I'd propose to use this to go through all accounts in a parliament CSV and return these results as a CSV or JSON (per parliamentarian?), which can then be viewed in some tbd interface. @grenwi: What do you think?
